/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gesthotel.ventanas;

import gesthotel.business.Ireservas;
import java.util.GregorianCalendar;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniellopezmesa
 */
public class Reservas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reservas
     */
    public Reservas() {
        initComponents();
        fecha.setValue(new GregorianCalendar().getTime());
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelOcupacion = new javax.swing.JPanel();
        fecha = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOcupacion = new javax.swing.JTable();
        jPanelLlegadas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelSalidas = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Listado de Reservas");

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(238, 238, 238));
        fecha.setBorder(null);
        fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("EEEE, d MMMM, yyyy"))));

        jTableOcupacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Daniel Lopez", "01/05/2017", "02/05/2017", "105"},
                {"Pedro Perez", "01/05/2017", "03/05/2017", "206"},
                {"Isabel Garcia", "04/05/2017", "06/05/2017", "108"},
                {"Maria Gutierrez", "04/05/2017", "08/05/2017", "200"}
            },
            new String [] {
                "Cliente", "Llegada", "Salida", "Habitación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableOcupacion);
        if (jTableOcupacion.getColumnModel().getColumnCount() > 0) {
            jTableOcupacion.getColumnModel().getColumn(0).setHeaderValue("Cliente");
            jTableOcupacion.getColumnModel().getColumn(1).setHeaderValue("Llegada");
            jTableOcupacion.getColumnModel().getColumn(2).setHeaderValue("Salida");
            jTableOcupacion.getColumnModel().getColumn(3).setHeaderValue("Habitación");
        }

        javax.swing.GroupLayout jPanelOcupacionLayout = new javax.swing.GroupLayout(jPanelOcupacion);
        jPanelOcupacion.setLayout(jPanelOcupacionLayout);
        jPanelOcupacionLayout.setHorizontalGroup(
            jPanelOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOcupacionLayout.createSequentialGroup()
                .addGroup(jPanelOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOcupacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                    .addComponent(fecha))
                .addContainerGap())
        );
        jPanelOcupacionLayout.setVerticalGroup(
            jPanelOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOcupacionLayout.createSequentialGroup()
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ocupación", jPanelOcupacion);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Daniel López",  new Integer(2), "03/05/20175", "1xMEDIA", "105"},
                {"Jesús García",  new Integer(3), "06/05/2017", "2xADULTOS", "206"},
                {"María Hidalgo",  new Integer(1), "04/05/2017", "2xMEDIA", "109"},
                {"Beatriz Aguilar",  new Integer(4), "09/05/2014", "4xCOMPLETA", "310"},
                {"Jaime Demos",  new Integer(2), "07/05/2017", "5xADULTOS", "208"},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Noches", "Llegada", "Pax + Régimen", "Habitación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Mañana");

        jButton2.setText("Hoy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Semana");

        jButton4.setText("Ayer");

        javax.swing.GroupLayout jPanelLlegadasLayout = new javax.swing.GroupLayout(jPanelLlegadas);
        jPanelLlegadas.setLayout(jPanelLlegadasLayout);
        jPanelLlegadasLayout.setHorizontalGroup(
            jPanelLlegadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLlegadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLlegadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLlegadasLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelLlegadasLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jButton3))))
        );
        jPanelLlegadasLayout.setVerticalGroup(
            jPanelLlegadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLlegadasLayout.createSequentialGroup()
                .addGroup(jPanelLlegadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        jTabbedPane1.addTab("Llegadas", jPanelLlegadas);

        jButton5.setText("Ayer");

        jButton6.setText("Hoy");

        jButton7.setText("Mañana");

        jButton8.setText("Semana");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Daniel López", "2", "03/05/2017", "1xADULTO", "105"},
                {"Jaime Demos", "4", "11/05/2017", "5xMEDIA", "310"},
                {"Beatriz Jiménez", "2", "06/05/2017", "2xADULTOS", "206"},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Noches", "Salida", "Pax+Régimen", "Habitación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelSalidasLayout = new javax.swing.GroupLayout(jPanelSalidas);
        jPanelSalidas.setLayout(jPanelSalidasLayout);
        jPanelSalidasLayout.setHorizontalGroup(
            jPanelSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalidasLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelSalidasLayout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8))
        );
        jPanelSalidasLayout.setVerticalGroup(
            jPanelSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalidasLayout.createSequentialGroup()
                .addGroup(jPanelSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salidas", jPanelSalidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanelLlegadas;
    private javax.swing.JPanel jPanelOcupacion;
    private javax.swing.JPanel jPanelSalidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableOcupacion;
    // End of variables declaration//GEN-END:variables
}
