/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gesthotel.ventanas;

import gesthotel.business.Ireservas;
import java.util.GregorianCalendar;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniellopezmesa
 */
public class Reservas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reservas
     */
    public Reservas() {
        initComponents();
        fecha.setValue(new GregorianCalendar().getTime());
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelOcupacion = new javax.swing.JPanel();
        fecha = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOcupacion = new javax.swing.JTable();
        jPanelLlegadas = new javax.swing.JPanel();
        jPanelSalidas = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listado de Reservas");

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(238, 238, 238));
        fecha.setBorder(null);
        fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("EEEE, d MMMM, yyyy"))));

        jTableOcupacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Daniel Lopez", "01/05/2017", "02/05/2017", "105"},
                {"Pedro Perez", "01/05/2017", "03/05/2017", "206"},
                {"Isabel Garcia", "04/05/2017", "06/05/2017", "108"},
                {"Maria Gutierrez", "04/05/2017", "08/05/2017", "200"}
            },
            new String [] {
                "Cliente", "Llegada", "Salida", "Habitación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableOcupacion);
        if (jTableOcupacion.getColumnModel().getColumnCount() > 0) {
            jTableOcupacion.getColumnModel().getColumn(0).setHeaderValue("Cliente");
            jTableOcupacion.getColumnModel().getColumn(1).setHeaderValue("Llegada");
            jTableOcupacion.getColumnModel().getColumn(2).setHeaderValue("Salida");
            jTableOcupacion.getColumnModel().getColumn(3).setHeaderValue("Habitación");
        }

        javax.swing.GroupLayout jPanelOcupacionLayout = new javax.swing.GroupLayout(jPanelOcupacion);
        jPanelOcupacion.setLayout(jPanelOcupacionLayout);
        jPanelOcupacionLayout.setHorizontalGroup(
            jPanelOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOcupacionLayout.createSequentialGroup()
                .addGroup(jPanelOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fecha, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOcupacionLayout.setVerticalGroup(
            jPanelOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOcupacionLayout.createSequentialGroup()
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ocupación", jPanelOcupacion);

        javax.swing.GroupLayout jPanelLlegadasLayout = new javax.swing.GroupLayout(jPanelLlegadas);
        jPanelLlegadas.setLayout(jPanelLlegadasLayout);
        jPanelLlegadasLayout.setHorizontalGroup(
            jPanelLlegadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanelLlegadasLayout.setVerticalGroup(
            jPanelLlegadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Llegadas", jPanelLlegadas);

        javax.swing.GroupLayout jPanelSalidasLayout = new javax.swing.GroupLayout(jPanelSalidas);
        jPanelSalidas.setLayout(jPanelSalidasLayout);
        jPanelSalidasLayout.setHorizontalGroup(
            jPanelSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanelSalidasLayout.setVerticalGroup(
            jPanelSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Salidas", jPanelSalidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField fecha;
    private javax.swing.JPanel jPanelLlegadas;
    private javax.swing.JPanel jPanelOcupacion;
    private javax.swing.JPanel jPanelSalidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableOcupacion;
    // End of variables declaration//GEN-END:variables
}
